CREATE TABLE IF NOT EXISTS drzava(drzavaID int, naziv text, glavni_grad int, primary key (drzavaID), foreign key (glavni_grad) references grad(gradID));
CREATE TABLE IF NOT EXISTS grad(gradID int, naziv text, broj_stanovnika int, drzava int, primary key (gradID), foreign key (drzava) references drzava(drzavaID));
INSERT INTO grad VALUES (1, 'Pariz', 2140526, 1);
INSERT INTO grad VALUES (2, 'London', 7355400, 2);
INSERT INTO grad VALUES (3, 'Manchester', 441200, 2);
INSERT INTO grad VALUES (4, 'Graz', 286686, 3);
INSERT INTO grad VALUES (5, 'Beč', 1867582, 3);
INSERT INTO drzava VALUES (1, 'Francuska', 1);
INSERT INTO drzava VALUES (2, 'Engleska', 2);
INSERT INTO drzava VALUES (3, 'Austrija', 5);